apiVersion: v1
kind: service
metadata:
  name: nginx+-
spec: 
  type: LoadBalancer
  selector:
   app: nginx
   demo: helm
  ports:
  - protocol: TCP
    port: 80  #service-port
    targetport: 80  #container-port